version: 2.19.0

services:
  db:
    image: 'postgres:13-alpine'
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: Musik