#SPRING CONFIGURATION
spring:
  liquibase:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    jdbc:
      initialize-schema: always
  application:
    name: Truck
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/MusicHub
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 87654321
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: false
#SERVER
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
