#SPRING CONFIGURATION
spring:
  liquibase:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  batch:
    jdbc:
      initialize-schema: always
  application:
    name: MusicHub
  datasource:
    url: jdbc:postgresql://localhost:5432/MusicHub
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 87654321
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: false
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
